modLoader = "javafml"
loaderVersion = "*"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = "${description}"
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[mixins]]
config = "${id}-common.mixins.json"

[[dependencies.${id}]]
modId="cloth_config"
type="optional"
mandatory=false
versionRange="[${cloth_config_version},)"
ordering="NONE"
side="CLIENT"